### ISSUE TITLE
Downloadable binary releases for macOS?

### ISSUE THREAD

**Issue by jaytaylor** [martanne/vis#633]
Hi,

I'd really like to try out vis, but so far have not succeeded in building it on macOS.  Is there any chance prebuilt binaries can be included in the github releases as downloads?  Or perhaps pushed to homebrew so it's installable via `brew install vis`?

**Comment by george-b** [comment]
See https://github.com/Homebrew/homebrew-core/pull/127

**Comment by herrbischoff** [comment]
There is now a new formula in homebrew-core: https://github.com/Homebrew/homebrew-core/blob/master/Formula/vis.rb

Unfortunately, when running it, it throws and error:

```
.../Cellar/vis/0.4/libexec/share/vis/themes/default-256.lua:23: attempt to index a nil value (local 'lexers')
```

As well as:

```
WARNING: could not find lpeg module
```

![screen shot 2018-01-21 at 01 31 49](https://user-images.githubusercontent.com/8957346/35189461-2b93d402-fe4b-11e7-8316-fcfe237a03e3.png)

**Comment by martanne** [comment]
Your first issue (theme loading when lpeg is not found) should be fixed by 5b8042ab1aa986d27e8974dbffe96bda6af61faf.

The real problem is that homebrew build/formula doesn't find the Lua `lpeg` module (or that [vis' package detection](https://github.com/martanne/vis/blob/5b8042ab1aa986d27e8974dbffe96bda6af61faf/lua/vis.lua#L101-L125) is buggy). I'm not sure why that is the case. Someone with a macOS system at hand should investigate that @esdf, @DomT4, @soveran, @tonchis ...

**Comment by herrbischoff** [comment]
Thanks for looking into it! Here's the build log (non-verbose) in case it helps. I built the HEAD version now and it indeed fixes the first issue.

```
$ brew reinstall vis --HEAD
==> Reinstalling vis
==> Cloning https://github.com/martanne/vis.git
Cloning into '/Users/mbischoff/Library/Caches/Homebrew/vis--git'...
remote: Counting objects: 241, done.
remote: Compressing objects: 100% (227/227), done.
remote: Total 241 (delta 30), reused 55 (delta 6), pack-reused 0
Receiving objects: 100% (241/241), 447.05 KiB | 1.41 MiB/s, done.
Resolving deltas: 100% (30/30), done.
==> Checking out branch master
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.1-1.src.rock
Already downloaded: /Users/mbischoff/Library/Caches/Homebrew/vis--lpeg-1.0.1-1.rock
==> luarocks build lpeg --tree=/usr/local/Cellar/vis/HEAD-5b8042a/libexec/vendor
==> ./configure --prefix=/usr/local/Cellar/vis/HEAD-5b8042a/libexec
==> make install
==> Not running post_install as we're building a bottle
You can run it manually using `brew postinstall vis`
==> Caveats
To avoid a name conflict with the macOS system utility /usr/bin/vis,
this text editor must be invoked by calling `vise` ("vis-editor").
==> Summary
🍺  /usr/local/Cellar/vis/HEAD-5b8042a: 174 files, 1.1MB, built in 21 seconds
```

**Comment by DomT4** [comment]
> I'm not sure why that is the case.

Pretty sure it's a simple error in the env script, looking at the formula. Give me a minute.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/pull/23211

**Comment by josb** [comment]
I've been wanting to try vis so thank you for fixing this!

**Comment by DomT4** [comment]
Should be fixed now.

**Comment by herrbischoff** [comment]
Unfortunately, for me it is not. I have updated Homebrew, reinstalled vis though the formula with `--HEAD` and I still get

```
WARNING: could not find lpeg module
```

and no syntax highlighting working.

**Comment by DomT4** [comment]
I assume this is how it's supposed to look?

<img width="846" alt="screen shot 2018-01-23 at 22 48 58" src="https://user-images.githubusercontent.com/6998367/35305012-a4b8e0ca-008f-11e8-919d-5a5e983a3ad8.png">

**Comment by DomT4** [comment]
If you've tried `brew reinstall vis` and you're not seeing that can you provide the output of `brew info vis`, `cat $(which vise)` and an updated screenshot? Thanks.

**Comment by herrbischoff** [comment]
Digging a little deeper, here's the content of `cat /usr/local/bin/vise`:

```
#!/bin/sh
LUA_PATH="/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/share/lua/5.3/?.lua"
LUA_CPATH="/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/lib/lua/5.3/?.so"
VIS_BASE=/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec
VIS_PATH=$VIS_BASE/share/vis $VIS_BASE/bin/vis $@
```

The `?`'s look suspicious to me. Is that correct?

**Comment by DomT4** [comment]
> The ?'s look suspicious to me. Is that correct?

Yeah. It's just Lua for _"everything in this directory please"_.

**Comment by herrbischoff** [comment]
```
$ brew info vis
vis: stable 0.4 (bottled), HEAD
Vim-like text editor
https://github.com/martanne/vis
/usr/local/Cellar/vis/HEAD-5b8042a_1 (174 files, 1.1MB) *
  Built from source on 2018-01-23 at 23:41:50
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/vis.rb
==> Dependencies
Required: libtermkey ✔, lua ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To avoid a name conflict with the macOS system utility /usr/bin/vis,
this text editor must be invoked by calling `vise` ("vis-editor").
```

**Comment by herrbischoff** [comment]
<img width="1425" alt="screen shot 2018-01-23 at 23 55 41" src="https://user-images.githubusercontent.com/8957346/35305267-050dba82-0099-11e8-9694-c04f92920ed8.png">

**Comment by DomT4** [comment]
Well. That's weird.

Let's prod a few other things:
* `lua -v`
* `env | grep LUA_`

**Comment by herrbischoff** [comment]
```
$ lua -v
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
```

```
$ env | grep LUA_

```

The latter one strikes me as wrong since it's empty.

**Comment by DomT4** [comment]
> The latter one strikes me as wrong since it's empty.

It's expected. The script only sets the arguments locally, not globally.

Can you try `brew rm vise && brew install vise` and see if you have the same issue? That'll install the stable version. I'm pretty sure this is something local to you in terms of a problem but quite what at this point isn't wildly obvious.

**Comment by herrbischoff** [comment]
When I use plain Bash and manually export the environment variables for Lua, it works. However, simply running `vise` in Bash without exporting them manually beforehand does not work.

**Comment by herrbischoff** [comment]
Surely you meant `vis` instead of `vise`... ;)

I have done so and as expected both original errors reappear as the fix for the lexer error is not in place in the release version.

**Comment by DomT4** [comment]
> Surely you meant vis instead of vise... ;)

Heh, good spot, was fixed pretty quickly & ya still noticed 😸.

Let's try this:
```
chmod 0777 $(which vise)
nano $(which vise)
```
And then tweak it to vomit the variables:

```bash
#!/bin/sh
LUA_PATH="/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/share/lua/5.3/?.lua"
LUA_CPATH="/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/lib/lua/5.3/?.so"
VIS_BASE=/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec
echo $LUA_PATH $LUA_CPATH $VIS_BASE
VIS_PATH=$VIS_BASE/share/vis $VIS_BASE/bin/vis $@
```

**Comment by herrbischoff** [comment]
Here you go:

```
/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/share/lua/5.3/?.lua /usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/lib/lua/5.3/?.so /usr/local/Cellar/vis/HEAD-5b8042a_1/libexec
```

**Comment by herrbischoff** [comment]
I tried something:

```
luarocks install lpeg
```

Afterwards it works. Maybe you have lpeg globally installed?

**Comment by DomT4** [comment]
Yeah, that looks right. This is odd. Can anyone else reproduce the issues @herrbischoff is having even after running `brew update && brew upgrade vis`?

> Maybe you have lpeg globally installed?

I did, but still works fine even after I've uninstalled it.

```
~> mdfind lpeg
/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/lib/lua/5.3/lpeg.so
/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/lib/luarocks/rocks-5.3/lpeg/1.0.1-1/lpeg-1.0.1-1.rockspec
/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/lib/luarocks/rocks-5.3/lpeg
/usr/local/var/homebrewcache/vis--lpeg-1.0.1-1.rock
/usr/local/Cellar/nmap/7.60/share/nmap/nselib/lpeg.luadoc
/usr/local/Cellar/nmap/7.60/share/nmap/nselib/lpeg-utility.lua
/usr/local/texlive/2017basic/texmf-dist/tex/luatex/lualibs/lualibs-lpeg.lua
/usr/local/texlive/2017basic/texmf-dist/tex/luatex/luaotfload/fontloader-l-lpeg.lua
```

```
~> vise /usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/share/lua/5.3/re.lua
```
Produces the same output as seen in https://github.com/martanne/vis/issues/633#issuecomment-359958406.

**Comment by herrbischoff** [comment]
Here's my search:

```
$ mdfind lpeg
/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/lib/lua/5.3/lpeg.so
/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/lib/luarocks/rocks-5.3/lpeg/1.0.1-1/lpeg-1.0.1-1.rockspec
/usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/vendor/lib/luarocks/rocks-5.3/lpeg
/usr/local/Cellar/nmap/7.60/share/nmap/nselib/lpeg.luadoc
/usr/local/Cellar/nmap/7.60/share/nmap/nselib/lpeg-utility.lua
/usr/local/texlive/2016/texmf-dist/tex/context/base/mkiv/l-lpeg.lua
/usr/local/texlive/2016/texmf-dist/tex/luatex/lualibs/lualibs-lpeg.lua
/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/fontloader-l-lpeg.lua
/Applications/mame0183-64bit/plugins/json/init.lua
```

**Comment by DomT4** [comment]
My current advice would be to leave `lpeg` installed globally and run with that until other people pop up here to say they're still having issues or not having issues. I'm pretty sure it's something local to you but other people confirming/denying that would be helpful at this point.

**Comment by jaytaylor** [comment]
I'm excited, `brew install vis` just worked for me, and `vise` is running just fine!

Marking this one closed..

thanks everyone!

**Comment by herrbischoff** [comment]
@jaytaylor: Good to hear that it works for you. How about leaving this open until more feedback is in?

**Comment by martanne** [comment]
While running `:help Lua` should show the paths as the editor sees them.

Thanks for packaging vis, I updated the [distribution package list](https://github.com/martanne/vis/wiki/Distribution-Packages).

**Comment by tonchis** [comment]
@DomT4 I was able to reproduce @herrbischoff problem. I `brew install vis`, but was only able to load `lpeg` after installing it globally (I probably have something wrong with my `luarocks` setup, because I had to use `sudo` to do it).

Another thing I noticed is that the other `vis` utilities, like `vis-open`, are apparently not installed because doing `:e .` throws a `command not found: vis-open` error. Can anyone else verify this?

Thanks for all the work debugging this!

**Comment by herrbischoff** [comment]
@martanne, here's my `:help Lua` output:

```
<KP8>
  <KP9>
  <KPEnter>
  <KPPlus>
  <KPMinus>
  <KPMult>
  <KPDiv>
  <KPComma>
  <KPPeriod>
  <KPEquals>

 Lua paths used to load runtime files (? will be replaced by filename):

  /usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/share/vis/?.lua
  /Users/mbischoff/.config/vis/?.lua
  /etc/vis/?.lua
  /usr/local/Cellar/vis/HEAD-5b8042a_1/libexec/share/vis/?.lua
  /usr/local/share/lua/5.3/?.lua
  /usr/local/share/lua/5.3/?/init.lua
  /usr/local/lib/lua/5.3/?.lua
  /usr/local/lib/lua/5.3/?/init.lua

 Lua paths used to load C libraries (? will be replaced by filename):

  /usr/local/lib/lua/5.3/?.so
  /usr/local/lib/lua/5.3/loadall.so
```

Does this look correct to you or is something obvious amiss?

**Comment by herrbischoff** [comment]
By the way, I just stumbled about a similar issue regarding other software commented on by @DomT4: https://github.com/Homebrew/legacy-homebrew/pull/41288#issuecomment-118508488

It appears the problems regarding Lua and Homebrew are nothing new — the issue is from 2015. Wouldn't it be better to have the mechanism mentioned there in place (halting installation, prompting the user to install lpeg manually)?

**Comment by martanne** [comment]
@herrbischoff your Lua C path section is missing the reference to `/usr/local/Cellar/...`

The reason for this is that the `vise` wrapper script does not actually export the `LUA_{C,}PATH` environment variables to the editor process. As currently written only `VIS_PATH` has an effect (which can also be observed in the help output above).

Pre-pending `export` to the first two lines of the wrapper script should fix it.

The issues mentioned by @tonchis (missing helper utilities) can likely be fixed by changing the wrapper to add the location of the vis binary as a first element to `$PATH`.

**Comment by herrbischoff** [comment]
@martanne: AHA! That fixed it. Thanks for looking into it! :)

@DomT4: That's probably worth adjusting if this fixes it for others as well. In that case, please disregard my previous comment.

**Comment by jaytaylor** [comment]
@herrbischoff As you wish :)

**Comment by DomT4** [comment]
> Another thing I noticed is that the other vis utilities, like vis-open, are apparently not installed because doing :e . throws a command not found: vis-open error. Can anyone else verify this?

Not sure quite why it was done this way to be honest, but they are installed, just "privately". They exist in `/usr/local/opt/vis/libexec/bin` whereas only the main executable is being installed as `vise` into the main `bin`.

> Pre-pending export to the first two lines of the wrapper script should fix it.

Yes, it does. We've hit this issue elsewhere before but it's an inconsistent one, seemingly.

> As there is obviously still no mechanism for Lua resources in Homebrew yet, wouldn't it be better to have the mechanism mentioned there in place

I object to the obviously, on the grounds that we've had a broadly working solution for vendoring Lua dependencies for quite some time now 😆. One hiccup here does not a failed system make.

> The issues mentioned by @tonchis (missing helper utilities) can likely be fixed by changing the wrapper to add the location of the vis binary as a first element to $PATH.

Where are these expected to live? In https://github.com/Homebrew/homebrew-core/pull/23256 I've just moved them into the main `bin`. Is that... legit?

**Comment by herrbischoff** [comment]
> I object to the obviously, on the grounds that we've had a broadly working solution for vendoring Lua dependencies for quite some time now 😆. One hiccup here does not a failed system make 😄.

You're right of course. Obviously and obvious oversight on my part... :D

**Comment by herrbischoff** [comment]
Just a quick heads-up: the `0.4_2` version of the formula works for me out-of-the-box — no global lpeg module, no HEAD formula, just works. Hooray!

**Comment by tonchis** [comment]
Can confirm `brew install vis` working as expected 🎉 

One million karma points for @DomT4 for his efforts. Thank you!

**Comment by DomT4** [comment]
> Obviously and obvious oversight on my part... 

Heh, no worries. My reply was fairly tongue-in-cheek. Lua handling did get a lot of stick in Homebrew for a long time so I tend to try and be a little like "hey we came up with a system that isn't _completely_ awful in the end please check again" where I get the opportunity 😸.

Glad folks are having better luck with the new version of the formula. Thanks for confirming!

**Comment by josb** [comment]
```
jbackus-m01:~% brew install vis --HEAD
Updating Homebrew...
==> Cloning https://github.com/martanne/vis.git
Updating /Users/jbackus/Library/Caches/Homebrew/vis--git
==> Checking out branch master
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.1-1.src.rock
Already downloaded: /Users/jbackus/Library/Caches/Homebrew/vis--lpeg-1.0.1-1.rock
==> luarocks build lpeg --tree=/usr/local/Cellar/vis/HEAD-5963289_2/libexec/vendor
==> ./configure --prefix=/usr/local/Cellar/vis/HEAD-5963289_2
==> make install
==> Caveats
To avoid a name conflict with the macOS system utility /usr/bin/vis,
this text editor must be invoked by calling `vise` ("vis-editor").
==> Summary
🍺  /usr/local/Cellar/vis/HEAD-5963289_2: 179 files, 1.1MB, built in 11 seconds
jbackus-m01:~% vise -v
vis 5963289 +curses +lua +tre
jbackus-m01:~%```
Note no `+lpeg`. Is this expected?

**Comment by tonchis** [comment]
@josb I leave it for others with more context than me to confirm, but `lpeg` being a runtime dependency for syntax highlighting doesn't show up as one of the compiled options in `vis -v`

**Comment by josb** [comment]
That makes sense, @tonchis . Thank you. Looks like vis uses runtime object loading for this.

My question was triggered by the seeming absence of syntax highlighting, which turns out is caused by the theme I'm using (acme). Removing the theme from my visrc makes things work again.
